# Generated by Django 3.2.16 on 2024-05-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Pub_date',
            new_name='pub_date',
        ),
    ]
