# Generated by Django 3.2.16 on 2024-05-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_pub_date_post_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликованн'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликованн'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликованн'),
        ),
    ]
